apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: mysql
spec:
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: mysql
  clusterIP: None
