apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace }}
  name: php-sc
type: Opaque
data:
  username: {{ .Values.secret.username }} # base64 인코딩된 사용자 이름 사용.
  password: {{ .Values.secret.password }} # base64 인코딩된 비밀번호 사용.