apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: phpmyadmin
spec:
  type: {{ .Values.phpmyadmin.service.type }}
  ports:
    - port: {{ .Values.phpmyadmin.service.port }}
      targetPort: {{ .Values.phpmyadmin.service.port }}
      nodePort: {{ .Values.phpmyadmin.service.nodePort }} # 노드에서 사용할 포트 번호 
  selector:
    app: phpmyadmin
